### ISSUE TITLE
[InvalidArgumentException]

### ISSUE THREAD

**Issue by luis9430** [kompo/laravel-vue-tailwind-starter#1]
hi i'm trying to install this package but i get this error

[InvalidArgumentException]
 Could not find package kompo/laravel-vue-tailwind-starter with stability stable.

my project´s name is
composer create-project --prefer-dist kompo/laravel-vue-tailwind-starter kompo

**Comment by kompo** [comment]
Hi @luis9430 ,

This starter pack will be replaced with something better soon. 

In the meantime, take a look at this (working) starter pack https://github.com/kompo/laravel-vue-starter and please install tailwind manually.

Thanks for your patience, many starter packs are being worked on!

**Comment by luis9430** [comment]
Hello, thanks for the answer  now I will try kompo!
