### ISSUE TITLE
Error installing tailwind

### ISSUE THREAD

**Issue by luis9430** [kompo/laravel-vue-tailwind-starter#2]
hi, what would be the best way to install tailwind with kompo? 

I am using this code in webpack.mix.js to require tailwind and run the command npm run dev

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })

when requiring webpack.mix.js file I get this error

`ERROR in ./node_modules/vue-kompo/js/query/query-layouts/Horizontal.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders> <template>
  <draggable
    v-bind="$_sortingAttributes"

ERROR in ./node_modules/vue-kompo/js/query/query-layouts/Kanban.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
   <div class="w-full overflow-x-auto">
 <div class="flex space-x-4">

ERROR in ./node_modules/vue-kompo/js/query/query-layouts/Masonry.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
ERROR in ./node_modules/vue-kompo/js/query/query-layouts/Table.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>

ERROR in ./node_modules/vue-kompo/js/query/query-layouts/TableForm.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders> <template>
  <div>
 <div class="table-responsive">

ERROR in ./node_modules/vue-kompo/js/query/query-layouts/Vertical.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
const mix = require('laravel-mix');
const tailwindcss =   ##require('tailwindcss')
`

**Comment by kompo** [comment]
Hi, 

This is because in the most recent version of mix, you need to indicate that you are using the vue-loader.
You have to add .vue() after the .js() call:

mix.js('resources/js/app.js', 'public/js').vue()
.sass('resources/sass/app.scss', 'public/css')
.options({
processCssUrls: false,
postCss: [ tailwindcss('./tailwind.config.js') ],
})
